app:
    secret-key: SNd09fMt2mUXUIk7iug2ycwieI/lVOiEeIlqmwLoDm4rwAZQow+DkHT0Kv/xpnf0c0A=  # This secret key can be any random string of
                          # characters.
                          #
                          # You should re-generate this for your application
                          # using:
                          #
                          # base64.b64encode(os.urandom(50)).decode('ascii')
    factory: skyportal.app_server.make_app

database:
    database: skyportal
    host: db
    port: 5432
    user: skyportal
    password:

server:
    # From https://console.developers.google.com/
    #
    # - Create Client ID
    # - Javascript origins: https://localhost:5000
    # - Authorized redirect URLs: http://localhost:5000/complete/google-oauth2/
    #
    # You need to have Google+ API enabled; it takes a few minutes to activate.

    auth:
        debug_login: False
        google_oauth2_key: 162885345684-2r5c865o49vruhr8to4u9sf1q8m4nr6d.apps.googleusercontent.com
        google_oauth2_secret: rELpsGHnovmg_GJFg8mHhLHe
